name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: "npm ci && npm run build:auth-lib"

      - name: Inject secret into environment.prod.ts
        run: sed -i "s/FIREBASE_API_KEY/${{ secrets.FIREBASEAPIKEY }}/g" projects/shell/src/environments/environment.prod.ts

      - run: "npm run build:shell"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALL_IN_ONE_ANGULAR }}"
          channelId: live
          projectId: all-in-one-angular
